### ISSUE TITLE
Date range UI does not update when minDate, maxDate or disabledDates gets re-evaluated

### ISSUE THREAD

**Issue by juliangums** [malzariey/filament-daterangepicker-filter#108]
I am using closures in the `->minDate()`, `->maxDate()` and `->disabledDates()` methods. If I use dd() inside of them I can see that they are re-evaluated when they should, but that does not seem to re-render the UI. Nothing changes there and they are still using the values from the first evaluation.

**Comment by juliangums** [comment]
Looks like this is because you are using `wire:ignore` in the view

**Comment by juliangums** [comment]
It works if I simply remove that. Any reason why it's there?

**Comment by juliangums** [comment]
Created a PR to remove it https://github.com/malzariey/filament-daterangepicker-filter/pull/109

**Comment by malzariey** [comment]
Thank you
