### ISSUE TITLE
Placeholder compiled without apply range

### ISSUE THREAD

**Issue by wit3** [malzariey/filament-daterangepicker-filter#11]
If you open input and doesn't click in any range, and then click outside, the input placeholder ( not the value in livewire component )
it's compiled as seen in the video below

```php
                    DateRangeFilter::make('date_issued')
                        ->label('Data Emissione')
                        ->columnSpan(3)
                        // ->withIndicater()
                        ,
                    DateRangeFilter::make('created_at')
                        ->label('Data Ricezione')
                        ->columnSpan(3)
                        // ->withIndicater()
                    ,
```
[Invoice Documents - Adascat.webm](https://user-images.githubusercontent.com/5450259/231778013-62083627-c217-4d6e-8c13-a107210e84d0.webm)

**Comment by malzariey** [comment]
Try the new option autoApply and confirm whether it fixes your issue?

**Comment by wit3** [comment]
> Try the new option autoApply and confirm whether it fixes your issue?

nope, autoApply setted to true didn't fix the issue

**Comment by malzariey** [comment]
Update to the latest version, solved
