### ISSUE TITLE
Dark mode color slightly off

### ISSUE THREAD

**Issue by kejedi** [malzariey/filament-daterangepicker-filter#111]
It seems the date picker uses some shades of a blueish gray rather than the filament gray when in dark mode

See here:

<img width="926" alt="Screenshot 2024-07-29 at 1 03 30 AM" src="https://github.com/user-attachments/assets/3a4d16ef-26c9-46e9-8f30-89cc410be35e">

Is there any way to fix this on my end?

I'm using the latest version of filament (3) and your package

**Comment by malzariey** [comment]
Did you follow this?

https://github.com/malzariey/filament-daterangepicker-filter?tab=readme-ov-file#styling
