### ISSUE TITLE
useRangeLabels() doesn't seam to work

### ISSUE THREAD

**Issue by buddhaCode** [malzariey/filament-daterangepicker-filter#114]
I can't get this feature to work. I can simply see no difference in my GUI.

With `useRangeLabels()`:
 
![SCR-20240731-laxs](https://github.com/user-attachments/assets/702c28e1-43f1-4570-ac5b-5ac0282a9abd)

The field should contain "Letzten 7 Tage" and not "25.07.2024 - 31.07.2024", shouldn't it?

Without `useRangeLabels()`:

![SCR-20240731-lbqc](https://github.com/user-attachments/assets/0cb3537e-3f15-4a5e-ba04-cf1bbdb26504)

**Comment by malzariey** [comment]
Could you share your code?

**Comment by buddhaCode** [comment]
Sure. The code is pretty basic:

```
DateRangeFilter::make('valued_at')
  ->label('Wertstellung am')
  ->timezone(config('app.display_timezone'))
  ->displayFormat('DD.MM.YYYY')
  ->format('d.m.Y')
  ->withIndicator()
  ->useRangeLabels(),
```

Did I describe the intention of the feature correctly?

**Comment by malzariey** [comment]
> ```
> DateRangeFilter::make('valued_at')
>   ->label('Wertstellung am')
>   ->timezone(config('app.display_timezone'))
>   ->displayFormat('DD.MM.YYYY')
>   ->format('d.m.Y')
>   ->withIndicator()
>   ->useRangeLabels(),
> ```

It works fine at my end, could you share a reproduction repo

![image](https://github.com/user-attachments/assets/ae16ea9d-bdd5-4157-a89e-0f61d6b0ca01)

**Comment by buddhaCode** [comment]
I found the cause of the issue. I am using `Date::use(CarbonImmutable::class);` in my `AppServiceProvider`. So all my dates are immutable. When I comment that out, it works perfectly fine. But I'm not sure why this is an issue.

**Comment by malzariey** [comment]
Thanks for reporting

**Comment by buddhaCode** [comment]
Do you have any idea why using immutables influences this feature?

**Comment by malzariey** [comment]
The package is not using immutable Carbon and might have made a mismatch when comparing dates
