### ISSUE TITLE
Alpine Expression Error: dateRangeComponent is not defined

### ISSUE THREAD

**Issue by EdduSoft** [malzariey/filament-daterangepicker-filter#121]
I'm getting the next error
Alpine Expression Error: dateRangeComponent is not defined

I just updated to the last version 3.0.3

![image](https://github.com/user-attachments/assets/352bb2e2-e775-4a92-a43e-752ee8af33dc)
When I try to click the filter, the filter does not display anything.

https://github.com/user-attachments/assets/f6f7c68a-f80c-4b56-af01-7570d813e335

Hope you can help me!

**Comment by EdduSoft** [comment]
`livewire.js?id=c4fc8c5d:1125 Alpine Expression Error: dateRangeComponent is not defined

Expression: "dateRangeComponent({
                state: window.Livewire.find('7vfMHNntnrq1ljFeMfJU').entangle('tableFilters.start_date.start_date'),
                name: 'tableFilters.start_date.start_date',
                alwaysShowCalendars: true,
                autoApply: false,
                linkedCalendars: true,
                autoUpdateInput: false,
                startDate: null,
                endDate: null,
                maxDate: null,
                minDate: null,
                timePicker: false,
                timePickerIncrement: 30,
                displayFormat: 'DD\/MM\/YYYY',
                disableCustomRange: false,
                opens: 'left',
                drops: 'auto',
                applyLabel: 'Apply',
                cancelLabel: 'Cancel',
                fromLabel: 'From',
                toLabel: 'To',
                customRangeLabel: 'Custom',
                january: 'January',
                february: 'February',
                march: 'March',
                april: 'April',
                may: 'May',
                june: 'June',
                july: 'July',
                august: 'August',
                september: 'September',
                october: 'October',
                november: 'November',
                december: 'December',
                sunday: 'Su',
                monday: 'Mo',
                tuesday: 'Tu',
                wednesday: 'We',
                thursday: 'Th',
                friday: 'Fr',
                saturday: 'Sa',
                firstDay: 1,
                ranges: JSON.parse('{\u0022Today\u0022:[\u00222024-08-22\u0022,\u00222024-08-22\u0022],\u0022Yesterday\u0022:[\u00222024-08-21\u0022,\u00222024-08-21\u0022],\u0022Last 7 Days\u0022:[\u00222024-08-16\u0022,\u00222024-08-22\u0022],\u0022Last 30 Days\u0022:[\u00222024-07-24\u0022,\u00222024-08-22\u0022],\u0022This Month\u0022:[\u00222024-08-01\u0022,\u00222024-08-31\u0022],\u0022Last Month\u0022:[\u00222024-07-01\u0022,\u00222024-07-31\u0022],\u0022This Year\u0022:[\u00222024-01-01\u0022,\u00222024-12-31\u0022],\u0022Last Year\u0022:[\u00222023-01-01\u0022,\u00222023-12-31\u0022]}'),
                separator: ' - ',
                useRangeLabels: false,
                disabledDates: [],
                handleValueChangeUsing: (value, name) => {
                    if (name == 'tableFilters.start_date.start_date') {
                        window.Livewire.find('7vfMHNntnrq1ljFeMfJU').set('tableFilters.start_date.start_date', value);
                    }
                },
            })"`

**Comment by EdduSoft** [comment]
I got it, I just deleted old view and run again the command

```
php artisan vendor:publish --tag="filament-daterangepicker-filter-views"
```

**Comment by malzariey** [comment]
Great, We have changed the way we are loading the assets
