### ISSUE TITLE
Dropdown Filter auto close when click on this year or Button Apply

### ISSUE THREAD

**Issue by KhairulAzmi21** [malzariey/filament-daterangepicker-filter#125]
https://github.com/user-attachments/assets/557d18d4-232c-42a8-8947-a3e3c8f2a5ef

I want to stay on dropdown filter even after click apply, how do i achieve this ?

**Comment by KhairulAzmi21** [comment]
Uploading Screen Recording 2024-09-13 at 15.11.09.mov…

**Comment by malzariey** [comment]
Fixed In beta version
