### ISSUE TITLE
firstDayOfWeek(0) does not set Sunday as the first day of the week

### ISSUE THREAD

**Issue by gasner** [malzariey/filament-daterangepicker-filter#127]
I encountered an issue where the firstDayOfWeek(0) function does not properly set Sunday as the first day of the week. The reason for this is a conditional check in the code in the DateRangePicker class, line 324:

`
if($day == null){
    return $this->getDefaultFirstDayOfWeek();
}
`
This condition incorrectly treats 0 as null, which prevents setting Sunday (0) as the first day. The condition should instead strictly check for null:

`
if($day === null){
    return $this->getDefaultFirstDayOfWeek();
}
`
This change ensures that 0 (Sunday) can be passed as a valid argument.

**Comment by malzariey** [comment]
Indeed, thanks for raising the issue.

Addressed in v3.1
