### ISSUE TITLE
Calendar position is changed, hover effect, not clickable icon

### ISSUE THREAD

**Issue by Valpuia** [malzariey/filament-daterangepicker-filter#17]
[Screencast from 05-26-2023 12:52:21 PM.webm](https://github.com/malzariey/filament-daterangepicker-filter/assets/28250303/55f18a72-31ce-4179-a3e7-a1582b5d9898)

As we can see from video

1. The label is not visible when hovering.. (in dark mode it is working)
2. Cannot open when clicking in icon (Filament default date can click on icon)
3. Biggest part: The calendar table move to the left side of panel when clicking Custom (twice) 

If the filter dropdown is still open then at first it close the filter dropdown, but if you click again in custom after dropdown closed then the calendar position is changed

Edited:

Custom click prevent when using `DateRangePicker` but error come in `DateRangeFilter`
Light mode hover and Icon is bug in both

`Using version ^1.2 for malzariey/filament-daterangepicker-filter`

**Comment by malzariey** [comment]
Check the latest update.
