### ISSUE TITLE
Mindate validation error

### ISSUE THREAD

**Issue by SyKenny** [malzariey/filament-daterangepicker-filter#25]
Using the date range picker field's mindate() gives a validation error. It validates the whole value instead of the first date in the string value.

```
DateRangePicker::make('date_covered')
    ->minDate(now()->startOfDay())
    ->maxDate(now()->startOfDay()->addYears(5))
    ->required(),
```

![image](https://github.com/malzariey/filament-daterangepicker-filter/assets/14899767/8ef955a2-20e1-4ffb-97b9-4755c991cc53)

**Comment by malzariey** [comment]
Will look into it, thanks for reporting
