### ISSUE TITLE
Style Not Match With Default Filament Style

### ISSUE THREAD

**Issue by untillnesss** [malzariey/filament-daterangepicker-filter#30]
the style of the Text Field type Date Range is not the same as the style provided by the default Filament, so it's a bit odd.

![image](https://github.com/malzariey/filament-daterangepicker-filter/assets/33585758/b149c5c6-5900-4d7e-8710-fa65130c2f14)

The code is like this

![image](https://github.com/malzariey/filament-daterangepicker-filter/assets/33585758/e5d4fd19-b558-4e47-9018-152011402d51)

**Comment by malzariey** [comment]
The white color is still following filament default font (Selected Value - Input Value). But you can always override the css.
![Filamentphp demo](https://github.com/malzariey/filament-daterangepicker-filter/assets/35528749/b0445bed-0f6f-4cc4-b810-039be935207b)

**Comment by untillnesss** [comment]
> The white color is still following filament default font (Selected Value - Input Value). But you can always override the css. ![Filamentphp demo](https://user-images.githubusercontent.com/35528749/260205996-b0445bed-0f6f-4cc4-b810-039be935207b.png)

How to override the css.?

**Comment by malzariey** [comment]
Register your style and use the following selector:

```
input[x-ref="daterange"] {
    color: yellow !important;
}
```
