### ISSUE TITLE
Date picker UI overflow is hidden on modals

### ISSUE THREAD

**Issue by eyounelson** [malzariey/filament-daterangepicker-filter#31]
<img height="250" alt="Screenshot 2023-08-16 at 13 50 13" src="https://github.com/malzariey/filament-daterangepicker-filter/assets/24621192/79676fc8-65dc-412c-9048-668656fbb286">

I can see the full date picker when I zoom my browser window out (Cltrl plus -)

<img height="250" alt="Screenshot 2023-08-16 at 13 50 22" src="https://github.com/malzariey/filament-daterangepicker-filter/assets/24621192/ab428891-da87-458b-b01f-db6162ae07a7">

It works as expected when used on a filter or regular form

**Comment by malzariey** [comment]
With version 2.5 you can now control where the picker will drop and choose UP direction to resolve the issue
