### ISSUE TITLE
Filters parsing fails when custom formats are being used

### ISSUE THREAD

**Issue by GeoSot** [malzariey/filament-daterangepicker-filter#57]
https://github.com/malzariey/filament-daterangepicker-filter/blob/16ad4caa5ca6addf6128db6ebeea88d0f7cca9c0/src/Filters/DateRangeFilter.php#L192

Exploding using space, may fail in case of custom formats like `M j, Y` as they already have spaces between them.
Maybe ` explode(' - ', $datesString); ` or ` explode( $tis->separator, $datesString); `  would be safer

**Comment by malzariey** [comment]
Addressed in latest version. v2.5.1

Thanks for raising the issue
