### ISSUE TITLE
Dark Mode CSS Support

### ISSUE THREAD

**Issue by sairiz** [malzariey/filament-daterangepicker-filter#63]
Hi,

Somehow, the CSS for darkmode doesnt work on your latest 2.4.0.

The css file generated from 2.3.1 start with .pointer-events-none but 2.4.0 start with .relative

You can compare the files from dist/filament-daterangepicker.css between 2.3.1 & 2.4.0

It seems there is a commit that doesnt get into 2.3.1 but brought in 2.4.0 that cause this.

Appreciate for your prompt fix. Thank you for your great plugin.

**Comment by malzariey** [comment]
Fixed in version #v2.4.1
