### ISSUE TITLE
When disabling ranges - sidebar still exists with no options

### ISSUE THREAD

**Issue by Sprunkas** [malzariey/filament-daterangepicker-filter#69]
I'm using disableRanges() and disableCustomRange() combined in my DateRangeFilter, but sidebar to pick custom range exists.

Now:
![image](https://github.com/malzariey/filament-daterangepicker-filter/assets/3625816/f3b56b5f-8c68-4a4f-b881-862a99cfefc3)

Expected behavior:
![image](https://github.com/malzariey/filament-daterangepicker-filter/assets/3625816/079bb0b1-480d-4d30-824c-8379f23dd471)

**Comment by malzariey** [comment]
Thank you for raising the issue.

Fixed with version 2.5.7.

Use `disableRanges()` method only to hide the range column.
