### ISSUE TITLE
Applying a format to the DateRangePicker field has no effect

### ISSUE THREAD

**Issue by mrstu84** [malzariey/filament-daterangepicker-filter#71]
I am using the date picker as a field (and not a filter) with displayFormat set to `DD-MM-YYY` and format set to `Y-m-d`. Each time the date range is return in the same format as the displayFormat, rather than format.

For example: 

When filtering between 01-01-1970 and 01-01-2024, here's my form schema  - 

```
DateRangePicker::make('date_range')
    ->label('Select date range')
    ->displayFormat('DD-MM-YYYY')
    ->format('Y-m-d'),
```

And the value is returned as `01-01-1970 - 01-01-2024`, rather than the expected value of `1970-01-01 - 2024-01-01`.

**Comment by malzariey** [comment]
`format` is used to define the date for Carbon to read from Javascript (Used mostly in query or default values) , it should match the displayFormat in (PHP format style). 

In your case just use displayFormat.

**Comment by mrstu84** [comment]
Thank you for coming back to me.

I would like the value to display as `01-01-1970 - 01-01-2024` in the input field and then be submitted to PHP as `1970-01-01 - 2024-01-01`, as mentioned in my original comment. I don't think you suggestion facilitates this.

**Comment by malzariey** [comment]
Do you mean you want to save the value in a different format to database?

**Comment by mrstu84** [comment]
Yes, that's correct. Maybe I am misunderstanding the documentation but I have read it that you can display one format in the input field and then submit that to the codebase and database in a different format. Hence the displayFormat and format attributes.

**Comment by malzariey** [comment]
Sorry at the moment, the feature is not available .

**Comment by mrstu84** [comment]
My misunderstanding. Thank you for coming back to me!
