### ISSUE TITLE
Layout issue on mobile

### ISSUE THREAD

**Issue by Umar-Farooq-Shafi** [malzariey/filament-daterangepicker-filter#72]
![image](https://github.com/malzariey/filament-daterangepicker-filter/assets/62417503/04a4ac18-91e5-4a28-9827-f44622938095)

**Comment by malzariey** [comment]
Refer to the following docs:

https://github.com/malzariey/filament-daterangepicker-filter?tab=readme-ov-file#drops-position

**Comment by Umar-Farooq-Shafi** [comment]
I did add the drop position. It doesn't matter if it's up or down; the overflow is still hidden.

**Comment by malzariey** [comment]
> I did add the drop position. It doesn't matter if it's up or down; the overflow is still hidden.

When you use
 `->drops(DropDirection::DOWN)`
 
 You would be able to scrolldown to select options

![Screenshot from 2024-04-26 13-15-12](https://github.com/malzariey/filament-daterangepicker-filter/assets/35528749/dda28b96-5c10-4e7b-8cef-7b8688b8e8fa)

You could also use
`->alwaysShowCalendar(false)`

to not show the calcendar unless custom dates are needed:
![Screenshot from 2024-04-26 13-19-43](https://github.com/malzariey/filament-daterangepicker-filter/assets/35528749/79ddeb20-8e13-4ef9-8820-fdb7689b81f4)
