### ISSUE TITLE
Display choice “aujourd\'hui" in French

### ISSUE THREAD

**Issue by riamehdi** [malzariey/filament-daterangepicker-filter#78]
As shown in the screenshot, there seems to have been an error in the string escaping with the key "today" in french “aujourd\'hui".

![brave_screenshot_localhost](https://github.com/malzariey/filament-daterangepicker-filter/assets/4673207/ea83c4f4-6a06-4e50-bebd-6286c6f59be2)

Thank you

**Comment by malzariey** [comment]
Addressed in version 2.7.0
