### ISSUE TITLE
DateRangePicker format is not adjust accordingly automatically when timepicker is enabled

### ISSUE THREAD

**Issue by Aamish26622** [malzariey/filament-daterangepicker-filter#83]
When enabling timepicker, the $data did not included the time values nor the time was displayed on frontend unless we manually call displayFormat() and set the format accordingly.

Ideally, when one used timepicker() function on the DateRangePicker, it should automatically format it according (unless they have manully called displayFormat()).

**Comment by Aamish26622** [comment]
Fixed in PR #82

**Comment by Aamish26622** [comment]
@majidalzariey any thoughts ?

**Comment by malzariey** [comment]
@Aamish26622 Thank you for your great PR, but I would prefer to resolve if any issue is available in the format with the getFormat() and getDisplayFormat rather than implementing alot of new variables. 

Might as well introduce a new API to enforce the format as it is.

**Comment by malzariey** [comment]
Fixed in beta version
