### ISSUE TITLE
Time picker does not open in a modal on mobile

### ISSUE THREAD

**Issue by OrangeJuiced** [malzariey/filament-daterangepicker-filter#93]
https://github.com/malzariey/filament-daterangepicker-filter/assets/22561290/16329c86-424a-46a6-b35b-acc41afc276f

On mobile, in a modal, tapping the time picker results in some odd behaviour. The time picker does not open, instead the entire date picker moves up. This does not happen outside a modal. See the attached screen recording.

**Comment by malzariey** [comment]
Thank you for your issue, 

I tried to repreducre the issue and it was not visible

[Screencast from 2024-07-02 01-12-40.webm](https://github.com/malzariey/filament-daterangepicker-filter/assets/35528749/6f56e689-da76-42a4-9d38-6c617669540a)

Please share a minimal issue repository to inspect further. 

Closing the issue as of now
