### ISSUE TITLE
Unable to select "today"

### ISSUE THREAD

**Issue by underdpt** [malzariey/filament-daterangepicker-filter#96]
Hello,

With this filter setup:

```php
DateRangeFilter::make('fecha_apertura')
    ->label('Fecha apertura')
    ->autoApply(true)
    ->linkedCalendars(true)
    ->withIndicator(),
```

I'm unable to select today date, nor by clicking on "Today" ("Hoy") or by double click on the date. It seems that current date is preselected and it only works if I select another date, then today:

![daterangefilter](https://github.com/malzariey/filament-daterangepicker-filter/assets/8122137/131c7f6c-ed91-42ee-a68c-973b99b4efad)

Any clue how to solve this?

**Comment by malzariey** [comment]
Fixed in version v2.8
